name: CI

on:
  pull_request:
  merge_group:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code has no lint errors
        uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad # Note: v3.5.0, using immutable reference for security reasons.

      - name: Check code is correctly formatted
        uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad # Note: v3.5.0, using immutable reference for security reasons.
        with:
          args: "format --check"
